"""
QuantTrade ML Pipeline — Strategy Execution Engine
Orchestrates all trading strategies, generates the unified trade log,
and computes rolling trade features for ML training.
"""
from __future__ import annotations

import sys
from pathlib import Path
from typing import Type

import numpy as np
import pandas as pd
from loguru import logger

sys.path.insert(0, str(Path(__file__).parent.parent.parent))
from config.settings import settings
from src.simulation.base_strategy import BaseStrategy, Trade
from src.simulation.strategies import (
    BollingerBandStrategy,
    BreakoutStrategy,
    MACrossoverStrategy,
    MomentumStrategy,
    RSIMeanReversionStrategy,
    SupportResistanceStrategy,
    TrendFollowingStrategy,
)

# ------------------------------------------------------------------ #
# Strategy Registry
# ------------------------------------------------------------------ #
STRATEGY_REGISTRY: dict[str, Type[BaseStrategy]] = {
    "momentum": MomentumStrategy,
    "ma_crossover": MACrossoverStrategy,
    "rsi_reversion": RSIMeanReversionStrategy,
    "bollinger": BollingerBandStrategy,
    "breakout": BreakoutStrategy,
    "trend_following": TrendFollowingStrategy,
    "support_resistance": SupportResistanceStrategy,
}


class SimulationEngine:
    """
    Runs all trading strategies on the feature-enriched DataFrame
    and returns a unified trade log with additional derived features.
    """

    def __init__(
        self,
        strategies: list[str] | None = None,
        initial_capital: float | None = None,
    ) -> None:
        self.strategy_names = strategies or list(STRATEGY_REGISTRY.keys())
        self.initial_capital = initial_capital or settings.initial_capital
        self._strategy_instances: list[BaseStrategy] = []
        self._all_trades: list[Trade] = []

    # ------------------------------------------------------------------ #
    # Public API
    # ------------------------------------------------------------------ #

    def run(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Run all strategies and return a trade log DataFrame.

        Args:
            df: Feature-enriched DataFrame with UTC DatetimeIndex

        Returns:
            Trade log DataFrame with ML-ready features
        """
        logger.info("Starting simulation | strategies={}", self.strategy_names)
        self._all_trades = []

        for name in self.strategy_names:
            strategy_cls = STRATEGY_REGISTRY.get(name)
            if strategy_cls is None:
                logger.warning("Unknown strategy: {}", name)
                continue

            try:
                strategy = strategy_cls(initial_capital=self.initial_capital)
                trades = strategy.run(df)
                self._all_trades.extend(trades)
                logger.info("  {} → {} trades", name, len(trades))
            except Exception as exc:
                logger.exception("Strategy {} failed: {}", name, exc)

        if not self._all_trades:
            logger.warning("No trades generated by any strategy")
            return pd.DataFrame()

        trade_log = self._build_trade_log()
        trade_log = self._add_trade_features(trade_log, df)

        logger.success(
            "Simulation complete | total_trades={} | win_rate={:.1%}",
            len(trade_log),
            trade_log["win"].mean() if "win" in trade_log.columns else 0.0,
        )
        return trade_log

    @property
    def all_trades(self) -> list[Trade]:
        return self._all_trades

    def get_strategy_summary(self, trade_log: pd.DataFrame) -> pd.DataFrame:
        """Return per-strategy performance summary."""
        if trade_log.empty:
            return pd.DataFrame()

        records = []
        for strategy_id in trade_log["strategy_id"].unique():
            strat_trades = trade_log[trade_log["strategy_id"] == strategy_id]
            n = len(strat_trades)
            wins = strat_trades["win"].sum()
            records.append({
                "strategy_id": strategy_id,
                "total_trades": n,
                "win_rate": wins / max(n, 1),
                "total_pnl_usd": strat_trades["pnl_usd"].sum(),
                "avg_pnl_usd": strat_trades["pnl_usd"].mean(),
                "avg_holding_bars": strat_trades["holding_bars"].mean(),
                "sharpe": self._quick_sharpe(strat_trades["pnl_usd"]),
                "max_drawdown": self._max_drawdown(strat_trades["pnl_usd"]),
            })
        return pd.DataFrame(records).sort_values("sharpe", ascending=False)

    # ------------------------------------------------------------------ #
    # Private Methods
    # ------------------------------------------------------------------ #

    def _build_trade_log(self) -> pd.DataFrame:
        """Convert Trade objects to a DataFrame."""
        records = [t.to_dict() for t in self._all_trades]
        df = pd.DataFrame(records)
        df["entry_time"] = pd.to_datetime(df["entry_time"], utc=True)
        df["exit_time"] = pd.to_datetime(df["exit_time"], utc=True)
        df = df.sort_values("entry_time").reset_index(drop=True)
        return df

    def _add_trade_features(
        self, trade_log: pd.DataFrame, market_df: pd.DataFrame
    ) -> pd.DataFrame:
        """
        Add ML-relevant features to each trade:
        - Rolling win rate (last N trades)
        - Rolling average PnL
        - Previous trade PnL
        - Trade index within strategy
        - Market context at entry time
        """
        df = trade_log.copy()

        # Per-strategy rolling statistics
        for strat_id in df["strategy_id"].unique():
            mask = df["strategy_id"] == strat_id
            subset = df[mask].copy()
            n = len(subset)

            # Rolling win rate (last 20 trades)
            subset["rolling_win_rate"] = subset["win"].rolling(20, min_periods=1).mean()
            subset["rolling_avg_pnl"] = subset["pnl_usd"].rolling(20, min_periods=1).mean()
            subset["rolling_std_pnl"] = subset["pnl_usd"].rolling(20, min_periods=1).std()
            subset["prev_trade_pnl"] = subset["pnl_usd"].shift(1).fillna(0)
            subset["prev_trade_win"] = subset["win"].shift(1).fillna(0).astype(int)
            subset["trade_index"] = range(n)
            subset["consecutive_wins"] = self._consecutive_count(subset["win"])
            subset["consecutive_losses"] = self._consecutive_count(~subset["win"])
            subset["cum_pnl"] = subset["pnl_usd"].cumsum()
            subset["peak_cum_pnl"] = subset["cum_pnl"].cummax()
            subset["drawdown_from_peak"] = subset["cum_pnl"] - subset["peak_cum_pnl"]

            df.loc[mask, subset.columns] = subset

        # ---- Market context at entry time ----
        market_cols = [
            "rsi_14", "adx", "macd_histogram", "bb_width", "atr_14_pct",
            "composite_bull_score", "is_london_session", "is_new_york_session",
            "is_london_ny_overlap", "realized_vol_24h", "return_24h",
            "nearby_event_impact_score", "mins_since_last_event",
        ]
        available_market_cols = [c for c in market_cols if c in market_df.columns]

        if available_market_cols:
            market_at_entry = market_df[available_market_cols].copy()
            market_at_entry.index = market_at_entry.index.tz_localize(None) if market_at_entry.index.tzinfo else market_at_entry.index

            entry_times = pd.to_datetime(df["entry_time"]).dt.tz_localize(None)
            merged = pd.merge_asof(
                df.assign(entry_time_naive=entry_times).sort_values("entry_time_naive"),
                market_at_entry.reset_index().rename(columns={"timestamp": "entry_time_naive"}),
                on="entry_time_naive",
                direction="backward",
            )
            df = merged.drop(columns=["entry_time_naive"], errors="ignore")

        return df

    @staticmethod
    def _consecutive_count(series: pd.Series) -> pd.Series:
        """Count consecutive True values."""
        result = pd.Series(0, index=series.index)
        count = 0
        for i, val in enumerate(series):
            if val:
                count += 1
            else:
                count = 0
            result.iloc[i] = count
        return result

    @staticmethod
    def _quick_sharpe(pnl_series: pd.Series) -> float:
        if len(pnl_series) < 2:
            return 0.0
        mean_pnl = pnl_series.mean()
        std_pnl = pnl_series.std()
        return float(mean_pnl / (std_pnl + 1e-10) * np.sqrt(252))

    @staticmethod
    def _max_drawdown(pnl_series: pd.Series) -> float:
        cum = pnl_series.cumsum()
        peak = cum.cummax()
        dd = (cum - peak)
        return float(dd.min())


def run_simulation(
    df: pd.DataFrame,
    strategies: list[str] | None = None,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """
    Run the full strategy simulation.

    Returns:
        (trade_log_df, strategy_summary_df)
    """
    engine = SimulationEngine(strategies=strategies)
    trade_log = engine.run(df)
    summary = engine.get_strategy_summary(trade_log)
    return trade_log, summary
